version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - nest-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: roberth456
      MYSQL_DATABASE: cats_db
      MYSQL_USER: hack4you
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    networks:
      - nest-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  nest-network:
volumes:
  mysql-volume:
